create table if not exists public.blocked_availability (
  id bigint generated by default as identity primary key,
  date date not null,
  period text not null check (period in ('all','09:00–12:00','13:00–16:00')),
  created_at timestamptz not null default now(),
  unique(date, period)
);

alter table public.blocked_availability enable row level security;
